# Generated by Django 5.1.4 on 2025-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='nullifier_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='facial_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='facial_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='wallet_address',
            field=models.CharField(default=0, max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
